---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: VSC, VASA Provider, SRA 문서가 제공됩니다
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes.html"
  - title: 빠른 시작
    url: "/qsg.html"
  - section: deploy
  - section: manage
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 릴리스 정보
      url: "/release-notes.html"
    - title: 빠른 시작
      url: "/qsg.html"
    - title: 배포 및 업그레이드
      url: "/deploy/concept-virtual-storage-console-overview.html"
    - title: 관리
      url: "/manage/concept-workflow-for-configuring-the-unified-appliance.html"
  - title: 더 많은 리소스
    links:
    - title: 이전 버전의 VSC, VASA Provider, SRA 관련 문서
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048
    - title: NetApp 기술 자료 - VSC, VASA 공급자, SRA를 지원합니다
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider
    - title: NetApp 가져오기 유틸리티 - 비디오
      url: https://www.youtube.com/watch?v=CEQmIEzNVfA
    - title: NetApp 커뮤니티 - VSC, VASA 공급자, SRA를 지원합니다
      url: https://community.netapp.com/t5/VMware-Solutions-Discussions/bd-p/vmware-solutions-discussions
