---
permalink: deploy/concept-standard-roles-packaged-with-virtual-appliance-for-vsc-vp-and-sra.html 
sidebar: sidebar 
keywords: standard, roles, packaged, virtual, appliance, vsc, vasa, provider, sra, 
summary: 'vCenter Server 권한 및 RBAC(역할 기반 액세스 제어)로 작업을 단순화하기 위해 (VSC)에서는 주요 VSC 작업을 수행할 수 있는 표준 VSC 역할을 제공합니다. VSC 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 합니다.' 
---
= VSC, VASA Provider, SRA를 위해 가상 어플라이언스와 함께 패키지로 제공되는 표준 역할입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server 권한 및 RBAC(역할 기반 액세스 제어)로 작업을 단순화하기 위해 (VSC)에서는 주요 VSC 작업을 수행할 수 있는 표준 VSC 역할을 제공합니다. VSC 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 합니다.

표준 VSC 역할에는 VSC 작업을 수행하는 데 필요한 VSC별 권한과 기본 vCenter Server 권한이 모두 포함되어 있습니다. 또한 지원되는 모든 vCenter Server 버전에서 필요한 권한을 가질 수 있도록 역할이 설정됩니다.

관리자는 필요에 따라 이러한 역할을 사용자에게 할당할 수 있습니다.

[NOTE]
====
VSC를 최신 버전으로 업그레이드하면 표준 역할이 자동으로 업그레이드되어 새로운 VSC 버전에서 작동합니다.

====
vSphere Client * Home * 페이지에서 * Roles * 를 클릭하여 VSC 표준 역할을 볼 수 있습니다.

VSC에서 제공하는 역할은 다음과 같은 작업을 수행할 수 있도록 지원합니다.

[cols="1a,1a"]
|===
| 역할 | 설명 


 a| 
VSC 관리자
 a| 
모든 VSC 작업을 수행하는 데 필요한 모든 네이티브 vCenter Server 권한과 VSC별 권한을 제공합니다.



 a| 
VSC 읽기 전용
 a| 
VSC에 대한 읽기 전용 액세스 제공

이러한 사용자는 액세스 제어 방식의 VSC 작업을 수행할 수 없습니다.



 a| 
VSC 프로비저닝
 a| 
스토리지 프로비저닝에 필요한 네이티브 vCenter Server 권한과 VSC별 권한을 모두 제공합니다.

다음 작업을 수행할 수 있습니다.

* 새 데이터 저장소를 생성합니다
* 데이터 저장소를 제거합니다
* 스토리지 용량 프로필에 대한 정보를 봅니다


|===