---
permalink: deploy/concept-recommended-ontap-roles-when-using-vsc-for-vmware-vsphere.html 
sidebar: sidebar 
keywords: recommended, ontap, roles, when, using, vsc, vmware, vsphere, 
summary: 'VMware vSphere용 가상 스토리지 콘솔 및 RBAC(역할 기반 액세스 제어)로 작업하기 위해 권장되는 여러 ONTAP 역할을 설정할 수 있습니다. 이러한 역할에는 VSC(VSC) 작업에서 실행되는 필요한 스토리지 작업을 수행하는 데 필요한 ONTAP 권한이 포함됩니다.' 
---
= VMware vSphere용 VSC를 사용할 때의 권장 ONTAP 역할
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 가상 스토리지 콘솔 및 RBAC(역할 기반 액세스 제어)로 작업하기 위해 권장되는 여러 ONTAP 역할을 설정할 수 있습니다. 이러한 역할에는 VSC(VSC) 작업에서 실행되는 필요한 스토리지 작업을 수행하는 데 필요한 ONTAP 권한이 포함됩니다.

새 사용자 역할을 생성하려면 ONTAP를 실행하는 스토리지 시스템에서 관리자로 로그인해야 합니다. 다음 중 하나를 사용하여 ONTAP 역할을 만들 수 있습니다.

* 9.7 이상
+
link:task-configure-user-role-and-privileges.html["사용자 역할 및 권한을 구성합니다"]

* RBAC ONTAP용 사용자 작성자 도구(ONTAP 9.6 이하를 사용하는 경우)
+
https://community.netapp.com/t5/Virtualization-Articles-and-Resources/RBAC-User-Creator-tool-for-VSC-VASA-Provider-and-Storage-Replication-Adapter-7-0/ta-p/133203["VSC, VASA 공급자 및 VMware vSphere용 스토리지 복제 어댑터 7.0용 RBAC 사용자 작성 툴"^]



각 ONTAP 역할에는 해당 역할의 자격 증명을 구성하는 연결된 사용자 이름 및 암호 쌍이 있습니다. 이러한 자격 증명을 사용하여 로그인하지 않으면 해당 역할과 연결된 스토리지 작업에 액세스할 수 없습니다.

보안 조치로서 VSC별 ONTAP 역할은 계층적으로 정렬됩니다. 즉, 첫 번째 역할이 가장 제한적인 역할이며 가장 기본적인 VSC 스토리지 운영 세트와 연관된 권한만 가집니다. 다음 역할에는 자신의 권한과 이전 역할과 연결된 모든 권한이 모두 포함됩니다. 각각의 추가 역할은 지원되는 스토리지 작업과 관련하여 덜 제한적입니다.

다음은 VSC를 사용할 때 권장되는 ONTAP RBAC 역할 중 일부입니다. 이러한 역할을 생성한 후에는 가상 시스템 프로비저닝과 같은 스토리지 관련 작업을 수행해야 하는 사용자에게 역할을 할당할 수 있습니다.

. 탐색
+
이 역할을 통해 스토리지 시스템을 추가할 수 있습니다.

. 스토리지 생성
+
이 역할을 사용하여 스토리지를 생성할 수 있습니다. 이 역할에는 검색 역할과 연결된 모든 권한도 포함됩니다.

. 스토리지 수정
+
이 역할을 사용하여 스토리지를 수정할 수 있습니다. 이 역할에는 검색 역할 및 스토리지 생성 역할과 연결된 모든 권한도 포함됩니다.

. 스토리지 폐기
+
이 역할을 사용하면 스토리지를 제거할 수 있습니다. 이 역할에는 검색 역할, 스토리지 생성 역할 및 스토리지 수정 역할과 연결된 모든 권한도 포함됩니다.



VASA Provider for ONTAP를 사용하는 경우 PBM(정책 기반 관리) 역할도 설정해야 합니다. 이 역할을 통해 스토리지 정책을 사용하여 스토리지를 관리할 수 있습니다. 이 역할을 수행하려면 "Discovery" 역할도 설정해야 합니다.
