---
permalink: deploy/concept-configure-high-availability-for-virtual-appliance-for-vsc-vasa-provider-and-sra.html 
sidebar: sidebar 
keywords: configuring, high, availability, virtual, appliance, vsc, vasa, provider, sra, 
summary: 'VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)용 가상 어플라이언스는 장애 시 VSC, VASA Provider, SRA의 무중단 기능을 제공할 수 있도록 HA(Virtual Storage Console) 구성을 지원합니다.' 
---
= VSC, VASA Provider, SRA를 위해 가상 어플라이언스에 대한 고가용성을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)용 가상 어플라이언스는 장애 시 VSC, VASA Provider, SRA의 무중단 기능을 제공할 수 있도록 HA(Virtual Storage Console) 구성을 지원합니다.

VSC, VASA Provider, SRA를 위한 가상 어플라이언스는 VMware vSphere(HA) 기능과 vSphere FT(Fault Tolerance) 기능을 사용하여 제공합니다. (HA) 솔루션을 사용하면 다음과 같은 원인으로 인한 운영 중단으로부터 신속하게 복구할 수 있습니다.

* 호스트 오류입니다
* 네트워크 오류입니다
* 가상 머신 장애(게스트 OS 장애)
* 애플리케이션(VSC, VASA Provider, SRA)이 충돌합니다


가상 어플라이언스의 경우 추가 구성이 필요하지 않습니다. 요구 사항에 따라 vCenter Server 및 ESXi 호스트만 VMware vSphere HA 기능 또는 vSphere FT 기능으로 구성해야 합니다. HA와 FT에는 모두 공유 스토리지와 함께 클러스터 호스트가 필요합니다. FT는 추가적인 요구 사항과 제한 사항이 있습니다.

가상 어플라이언스는 VMware vSphere HA 솔루션 및 vSphere FT 솔루션 외에도 VSC, VASA Provider 및 SRA 서비스를 항상 실행할 수 있도록 지원합니다. 가상 어플라이언스 감시 프로세스는 세 가지 서비스를 주기적으로 모니터링하여 어떤 종류의 장애가 감지되면 자동으로 다시 시작합니다. 이렇게 하면 응용 프로그램 오류를 방지할 수 있습니다.

[NOTE]
====
vCenter HA는 VSC, VASA Provider, SRA용 가상 어플라이언스에서 지원되지 않습니다.

====