---
permalink: deploy/concept-requirements-for-registering-vsc-in-multiple-vcenter-servers-environment.html 
sidebar: sidebar 
keywords: requirements, registering, vsc, multiple, vcenter, servers, environment, 
summary: '단일 VMware vSphere HTML5 클라이언트가 있는 환경에서 VMware vSphere용 Virtual Storage Console을 사용하는 경우 에서 여러 vCenter Server 인스턴스를 관리하는 경우 VSC와 vCenter Server 간에 1:1 페어링이 있을 수 있도록 각 vCenter Server에 VSC 인스턴스 하나를 등록해야 합니다. 이렇게 하면 단일 vSphere HTML5 클라이언트에서 연결된 모드와 연결되지 않은 모드 모두에서 vCenter 6.0 이상을 실행하는 모든 서버를 관리할 수 있습니다.' 
---
= 여러 vCenter Server 환경에 VSC를 등록하는 데 필요한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 VMware vSphere HTML5 클라이언트가 있는 환경에서 VMware vSphere용 Virtual Storage Console을 사용하는 경우 에서 여러 vCenter Server 인스턴스를 관리하는 경우 VSC와 vCenter Server 간에 1:1 페어링이 있을 수 있도록 각 vCenter Server에 VSC 인스턴스 하나를 등록해야 합니다. 이렇게 하면 단일 vSphere HTML5 클라이언트에서 연결된 모드와 연결되지 않은 모드 모두에서 vCenter 6.0 이상을 실행하는 모든 서버를 관리할 수 있습니다.

[NOTE]
====
vCenter Server에서 VSC를 사용하려면 관리할 모든 vCenter Server 인스턴스에 대해 VSC 인스턴스를 하나 이상 설정하거나 등록해야 합니다. 등록된 각 VSC 인스턴스의 버전은 동일해야 합니다.

====
연결된 모드는 vCenter Server 구축 중에 자동으로 설치됩니다. 연결 모드는 Microsoft ADAM(Active Directory Application Mode)을 사용하여 여러 vCenter Server 시스템에 데이터를 저장하고 동기화합니다.

vSphere HTML5 클라이언트를 사용하여 여러 vCenter Server에서 VSC 작업을 수행하려면 다음이 필요합니다.

* 관리하려는 VMware 인벤토리의 각 vCenter Server에는 고유한 1:1 페어링에 단일 VSC 서버가 등록되어 있어야 합니다.
+
예를 들어, VSC 서버 A에 등록된 VSC 서버 A, vCenter Server B에 등록된 VSC 서버 B, vCenter Server C에 등록된 VSC 서버 C 등의 작업을 수행할 수 있습니다.

+
vCenter Server A와 vCenter Server B 모두에 VSC 서버 A를 등록할 수 없습니다

+
VMware 인벤토리에 VSC 서버가 등록되지 않은 vCenter Server가 포함되어 있지만 VSC에 등록된 vCenter Server가 하나 이상 있는 경우, 그런 다음 VSC의 인스턴스를 확인하고 VSC를 등록한 vCenter Server에 대해 VSC 작업을 수행할 수 있습니다.

* SSO(Single Sign-On)에 등록된 각 vCenter Server에 대한 VSC별 View 권한이 있어야 합니다.
+
또한 올바른 RBAC 권한도 있어야 합니다.



vCenter Server를 지정해야 하는 작업을 수행하는 경우 * vCenter Server * 드롭다운 상자에 사용 가능한 vCenter Server가 영숫자 순서로 표시됩니다. 기본 vCenter Server는 항상 드롭다운 목록의 첫 번째 서버입니다.

스토리지의 위치를 알고 있는 경우(예: * Provisioning * 마법사를 사용하고 데이터 저장소가 특정 vCenter Server에서 관리하는 호스트에 있는 경우) vCenter Server 목록이 읽기 전용 옵션으로 표시됩니다. 이 문제는 vSphere Web Client에서 마우스 오른쪽 버튼 클릭 옵션을 사용하여 항목을 선택하는 경우에만 발생합니다.

VSC는 관리하지 않는 개체를 선택하려고 할 때 경고합니다.

VSC 요약 페이지에서 특정 vCenter Server를 기반으로 스토리지 시스템을 필터링할 수 있습니다. vCenter Server에 등록된 모든 VSC 인스턴스에 대한 요약 페이지가 나타납니다. 특정 VSC 인스턴스 및 vCenter Server와 연관된 스토리지 시스템을 관리할 수 있지만, VSC의 여러 인스턴스를 실행하는 경우 각 스토리지 시스템의 등록 정보를 별도로 유지해야 합니다.
