---
permalink: deploy/concept-vmware-fault-tolerance-for-vcenter-server.html 
sidebar: sidebar 
keywords: vsc, vmware, vsphere, fault, tolerance, 
summary: 'VMware vSphere FT(Fault Tolerance) 기능은 더 높은 수준에서 HA(Fault Tolerance)를 제공하며 데이터 또는 연결을 손실하지 않고 가상 머신을 보호할 수 있습니다. vCenter Server에서 VSC, VASA Provider 및 SRA를 위한 가상 어플라이언스에 대해 vSphere FT를 사용하거나 사용하지 않도록 설정해야 합니다.' 
---
= VMware vSphere 내결함성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere FT(Fault Tolerance) 기능은 더 높은 수준에서 HA(Fault Tolerance)를 제공하며 데이터 또는 연결을 손실하지 않고 가상 머신을 보호할 수 있습니다. vCenter Server에서 VSC, VASA Provider 및 SRA를 위한 가상 어플라이언스에 대해 vSphere FT를 사용하거나 사용하지 않도록 설정해야 합니다.

vSphere 라이센스가 사용자 환경의 가상 어플라이언스에 필요한 vCPU 수로 FT를 지원하는지 확인합니다(대규모 환경의 경우 vCPU 2개 이상, vCPU 4개).

vSphere FT를 사용하면 서버 장애가 발생하더라도 가상 머신을 지속적으로 운영할 수 있습니다. 가상 머신에서 vSphere FT가 설정되면 DRS(Distributed Resource Scheduler)가 선택한 다른 호스트(보조 가상 머신)에 운영 가상 머신의 복제본이 자동으로 생성됩니다. DRS가 활성화되어 있지 않으면 사용 가능한 호스트에서 대상 호스트가 선택됩니다. vSphere FT는 운영 가상 머신과 보조 가상 머신을 잠금 단계 모드로 작동하여 각 가상 머신이 운영 가상 머신의 실행 상태를 보조 가상 머신에 미러링합니다.

운영 가상 시스템에 장애를 일으키는 하드웨어 장애가 있는 경우 보조 가상 머신이 운영 가상 머신이 중지된 위치를 즉시 감지합니다. 보조 가상 시스템은 네트워크 연결, 트랜잭션 또는 데이터의 손실 없이 계속 실행됩니다.

시스템은 vCenter Server 인스턴스에 대해 vSphere FT를 구성하기 위한 CPU 요구 사항, 가상 머신 제한 요구 사항 및 라이센스 요구 사항을 충족해야 합니다.

HA를 구성하는 절차는 vCenter Server 버전에 따라 다릅니다. 예를 들어 다음 참조 링크를 사용하여 필요한 vCenter Server 버전을 선택하여 HA 구성 단계를 볼 수 있습니다.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["VMware vSphere 설명서: 내결함성 요구 사항, 제한 사항 및 라이센스"^]
