---
permalink: deploy/reference-key-points-about-assigning-and-modifying-permissions.html 
sidebar: sidebar 
keywords: key, points, about, assigning, modifying, permissions, vcenter, server, 
summary: vCenter Server 사용 권한을 사용할 때는 몇 가지 주요 사항을 염두에 두어야 합니다. VMware vSphere용 Virtual Storage Console 작업의 성공 여부는 권한이 할당된 위치 또는 권한이 수정된 후 사용자가 수행한 작업에 따라 달라집니다. 
---
= vCenter Server에 대한 권한을 할당하고 수정하는 방법에 대한 핵심 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server 사용 권한을 사용할 때는 몇 가지 주요 사항을 염두에 두어야 합니다. VMware vSphere용 Virtual Storage Console 작업의 성공 여부는 권한이 할당된 위치 또는 권한이 수정된 후 사용자가 수행한 작업에 따라 달라집니다.



== 권한 할당

vSphere 객체 및 작업에 대한 액세스를 제한하려면 vCenter Server 권한만 설정하면 됩니다. 그렇지 않으면 관리자로 로그인할 수 있습니다. 이 로그인을 통해 모든 vSphere 객체에 자동으로 액세스할 수 있습니다.

권한을 할당하는 위치에 따라 사용자가 수행할 수 있는 VSC 작업이 결정됩니다.

작업을 완료하려면 루트 개체와 같은 상위 수준에서 사용 권한을 할당해야 하는 경우가 있습니다. 이 경우는 작업에 특정 vSphere 객체에 적용되지 않는 권한(예: 작업 추적)이 필요하거나 vSphere가 아닌 객체(예: 스토리지 시스템)에 필요한 권한이 적용되는 경우에 해당합니다.

이러한 경우 사용 권한을 설정하여 자식 엔터티가 사용 권한을 상속할 수 있습니다. 하위 엔티티에 다른 권한을 할당할 수도 있습니다. 자식 엔터티에 할당된 권한은 항상 부모 엔터티로부터 상속된 권한을 재정의합니다. 즉, 루트 개체에 할당되고 자식 엔터티가 상속한 권한의 범위를 제한하는 방법으로 자식 엔터티에 대한 권한을 부여할 수 있습니다.


TIP: 회사의 보안 정책에 더 제한적인 권한이 필요한 경우를 제외하고 루트 개체(루트 폴더라고도 함)에 권한을 할당하는 것이 좋습니다.



== 사용 권한 및 비 vSphere 객체

생성한 권한은 vSphere가 아닌 객체에 적용됩니다. 예를 들어, 스토리지 시스템은 vSphere 객체가 아닙니다. 권한이 스토리지 시스템에 적용되는 경우, 권한을 할당할 수 있는 vSphere 개체가 없으므로 VSC 루트 개체에 해당 권한이 포함된 권한을 할당해야 합니다.

예를 들어, VSC 권한 "스토리지 시스템 추가/수정/건너뛰기"와 같은 권한을 포함하는 모든 권한은 루트 오브젝트 레벨에 할당되어야 합니다.



== 권한을 수정합니다

언제든지 하나의 권한을 수정할 수 있습니다.

권한 내에서 권한을 변경하는 경우 해당 권한과 연결된 사용자는 로그아웃한 다음 다시 로그인하여 업데이트된 권한을 활성화해야 합니다.
