---
permalink: deploy/task-enable-vasa-provider-for-configuring-virtual-datastores.html 
sidebar: sidebar 
keywords: enabling, vasa, provider, for, configuring, virtual, datastores, 
summary: 'VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)용 가상 어플라이언스에는 기본적으로 VASA Provider 기능이 활성화되어 있습니다. 각 VVol 데이터 저장소에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes) 데이터 저장소를 구성할 수 있습니다.' 
---
= 가상 데이터 저장소를 구성하기 위해 VASA Provider를 설정합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)용 가상 어플라이언스에는 기본적으로 VASA Provider 기능이 활성화되어 있습니다. 각 VVol 데이터 저장소에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes) 데이터 저장소를 구성할 수 있습니다.

.시작하기 전에
* vCenter Server 인스턴스를 설정하고 ESXi를 구성해야 합니다.
* VSC, VASA Provider, SRA를 위한 가상 어플라이언스를 구축해야 합니다.


.이 작업에 대해
VSC(Virtual Storage Console), VASA Provider 및 SRA(Storage Replication Adapter)용 가상 어플라이언스의 9.7.1 릴리즈로 업그레이드하기 전에 VASA Provider 기능을 사용하지 않도록 설정한 경우, 업그레이드 후에도 VASA Provider 기능은 비활성 상태로 유지됩니다. 이 릴리즈를 사용하면 VVOL 데이터 저장소에 대한 VVol 복제 기능을 활성화할 수 있습니다.

.단계
. VMware vSphere의 웹 사용자 인터페이스에 로그인합니다.
. vSphere Client에서 메뉴 [Virtual Storage Console] 을 클릭합니다.
. 설정 * 을 클릭합니다.
. 관리 설정 * 탭에서 * 기능 관리 * 를 클릭합니다.
. Manage Capabilities * 대화 상자에서 사용할 VASA Provider 확장을 선택합니다.
. VVOL 데이터 저장소의 복제 기능을 사용하려면 * VVol 복제 활성화 * 전환 버튼을 사용합니다.
. VSC, VASA Provider, SRA 및 관리자 암호를 위한 가상 어플라이언스의 IP 주소를 입력한 다음 * Apply * 를 클릭합니다.


.작업을 마친 후
ONTAP 9.6 또는 이전 클러스터를 사용하는 경우, SAN VVol VM 및 SAN VVol 데이터 저장소 보고서에 사용된 VVol 데이터 저장소 및 가상 시스템에 대한 세부 정보를 얻기 위해 VASA Provider에 등록해야 합니다. 그러나 ONTAP 9.7 이상을 사용하는 경우에는 VASA Provider에 등록할 필요가 없습니다.
