---
permalink: manage/concept-considerations-for-creating-and-editing-storage-capability-profiles.html 
sidebar: sidebar 
keywords: considerations, for, creating, and, editing, storage, capability, profiles, 
summary: 스토리지 용량 프로필을 생성 및 편집할 때 고려해야 할 사항에 대해 알고 있어야 합니다. 
---
= 스토리지 용량 프로파일을 생성 및 편집할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 용량 프로필을 생성 및 편집할 때 고려해야 할 사항에 대해 알고 있어야 합니다.

* AFF 시스템에서만 최소 IOPS를 구성할 수 있습니다.
* VVOL(가상 볼륨) 데이터 저장소 수준에서 QoS 메트릭을 구성할 수 있습니다.
+
이 기능을 사용하면 가상 데이터 저장소에 프로비저닝된 동일한 가상 머신의 서로 다른 VMDK에 다양한 QoS 메트릭을 할당할 수 있습니다.

* FAS 및 AFF 데이터 저장소 모두에 대해 스토리지 용량 프로필을 구성할 수 있습니다.
+
FAS 시스템의 경우 공간 예비 공간을 일반 또는 씬 공간으로 구성할 수 있지만 AFF 시스템의 경우 공간 예비 공간을 씬 공간으로 구성할 수 있습니다.

* 스토리지 용량 프로필을 사용하여 데이터 저장소에 대한 암호화를 제공할 수 있습니다.
* VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)용 가상 어플라이언스의 이전 버전에서 VSC, VASA Provider, SRA용 가상 어플라이언스의 최신 버전으로 업그레이드한 후에는 기존 스토리지 기능 프로필을 수정할 수 없습니다.
+
기존 스토리지 기능 프로필은 이전 버전과의 호환성을 위해 유지됩니다. 기본 템플릿을 사용하지 않는 경우 VSC, VASA Provider, SRA용 가상 어플라이언스의 최신 버전으로 업그레이드하는 동안 기존 템플릿이 재정의되어 스토리지 기능 프로필의 성능과 관련된 새로운 QoS 메트릭을 반영합니다.

* 기존 스토리지 기능 프로필을 수정하거나 사용하여 새 가상 데이터 저장소 또는 VM 스토리지 정책을 프로비저닝할 수 없습니다.
* 모든 새 데이터 저장소에 새 스토리지 용량 프로필을 사용해야 합니다.

