---
permalink: manage/concept-what-storage-capabilities-are.html 
sidebar: sidebar 
keywords: storage, capability, profiles, 
summary: 스토리지 기능은 특정 수준의 스토리지 성능, 스토리지 효율성 및 스토리지 기능과 연결된 스토리지 오브젝트의 암호화와 같은 기타 기능을 식별하는 스토리지 시스템 속성의 집합입니다. 
---
= 스토리지 용량에 대한 내용을 설명합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 기능은 특정 수준의 스토리지 성능, 스토리지 효율성 및 스토리지 기능과 연결된 스토리지 오브젝트의 암호화와 같은 기타 기능을 식별하는 스토리지 시스템 속성의 집합입니다.

기존 데이터 저장소의 경우 스토리지 용량 프로필을 사용하여 공통 특성을 사용하여 데이터 저장소를 일관되게 생성하고 QoS 정책을 해당 데이터 저장소에 할당할 수 있습니다. 프로비저닝 VSC를 사용하면 스토리지 기능 프로필과 일치하는 클러스터, SVM, 애그리게이트를 표시할 수 있습니다. Storage Mapping * 메뉴의 * global Auto-generate profiles * 옵션을 사용하여 기존 기존 데이터 저장소에서 스토리지 용량 프로파일을 생성할 수 있습니다. 프로필이 생성된 후에는 VSC를 사용하여 프로필과의 데이터 저장소 규정 준수를 모니터링할 수 있습니다.

VVOL 데이터 저장소와 함께 사용하면 프로비저닝 마법사에서 여러 스토리지 기능 프로필을 사용하여 데이터 저장소에 서로 다른 FlexVol 볼륨을 생성할 수 있습니다. VM 스토리지 정책을 사용하여 정의된 대로 적절한 FlexVol 볼륨에서 가상 머신에 대한 VVol을 자동으로 생성할 수 있습니다. 예를 들어, 성능 제한 및 암호화 또는 FabricPool와 같은 기타 기능에 대한 프로파일을 일반 스토리지 클래스에 생성할 수 있습니다. 나중에 가상 머신의 비즈니스 클래스를 나타내는 vCenter Server에서 VM 스토리지 정책을 생성하고 이름을 기준으로 적절한 스토리지 용량 프로필에 연결할 수 있습니다(예: 운영, 테스트, HR).

VVOL과 함께 사용할 경우 스토리지 기능 프로파일을 사용하여 개별 가상 머신의 스토리지 성능을 설정하고 성능 요구사항을 가장 충족하는 VVOL 데이터 저장소의 FlexVol 볼륨에 배치합니다. 성능에 대한 최소 및/또는 최대 IOPS로 QoS 정책을 지정할 수 있습니다. 처음에 가상 시스템을 프로비저닝할 때 기본 정책을 사용하거나 비즈니스 요구사항이 변경될 경우 나중에 VM 스토리지 정책을 변경할 수 있습니다.

그런 다음 vCenter Server는 LUN 또는 볼륨의 스토리지 기능을 해당 LUN 또는 볼륨에 프로비저닝된 데이터 저장소와 연결합니다. 이를 통해 가상 머신의 스토리지 프로필과 일치하는 데이터 저장소에 가상 머신을 프로비저닝하고 데이터 저장소 클러스터의 모든 데이터 저장소에 동일한 스토리지 서비스 수준이 있는지 확인할 수 있습니다.

가상 스토리지 콘솔(VSC), VASA 공급자, SRA(Storage Replication Adapter)용 가상 어플라이언스를 사용하면 동일한 VVOL 데이터 저장소에서 다양한 IOPS 요구사항에 따라 가상 머신의 프로비저닝을 지원하는 새로운 스토리지 기능 프로필로 모든 가상 볼륨(VVOL) 데이터 저장소를 구성할 수 있습니다. VM 프로비저닝 워크플로를 IOPS 요구 사항으로 실행하는 동안 모든 VVOL 데이터 저장소가 호환되는 데이터 저장소 목록에 나열됩니다.

[NOTE]
====
6.5 이전 버전의 vCenter Server에 대해 가상 머신을 프로비저닝하거나 수정하려고 하면 " mAX_IOPS " 로 설정된 성능이 있는 저장소 기능 프로파일이 포함된 VVOL 데이터 저장소만 호환 데이터 저장소 목록에 나열됩니다. 나머지 VVOL 데이터 저장소는 호환되지 않는 데이터 저장소 목록에 나열됩니다. 이 분류를 무시하고 호환되지 않는 데이터 저장소 목록에서 모든 VVol 데이터 저장소를 선택하여 가상 시스템을 프로비저닝 또는 수정할 수 있습니다.

====