---
permalink: manage/concept-datastore-reports.html 
sidebar: sidebar 
keywords: datastore, reports, 
summary: 데이터 저장소 보고서는 기존 데이터 저장소 및 이러한 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 제공합니다. 
---
= 데이터 저장소 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 저장소 보고서는 기존 데이터 저장소 및 이러한 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 제공합니다.

기존 대시보드를 사용하면 vCenter Server의 데이터 저장소 및 가상 시스템과 관련된 잠재적인 문제를 검토하고 식별할 수 있습니다. 보고서를 보고, 정렬하고, 내보낼 수 있습니다. 기존 데이터 저장소 및 가상 머신 보고서의 데이터는 vCenter Server에서 제공합니다.

데이터 저장소는 다음과 같은 사전 정의된 보고서를 제공합니다.

* 데이터 저장소 보고서
* 가상 시스템 보고서




== 데이터 저장소 보고서

Datastore Report 메뉴에는 데이터 저장소에 대한 다음 매개 변수에 대한 정보가 제공됩니다.

* 데이터 저장소의 이름입니다
* 데이터 저장소 유형: NFS 또는 VMFS
* 여유 공간
* 사용된 공간
* 총 공간
* 사용된 공간의 비율입니다
* 사용 가능한 공간의 비율입니다
* IOPS
+
보고서에 데이터 저장소의 IOPS가 표시됩니다.

* 지연 시간
+
이 보고서에는 데이터 저장소의 지연 시간 정보가 표시됩니다.



보고서가 생성된 시간을 확인할 수도 있습니다. Datastore Report 메뉴를 사용하면 필요에 따라 보고서를 구성한 다음 * Export to CSV * 버튼을 사용하여 조직화된 보고서를 내보낼 수 있습니다. 보고서의 데이터 저장소 이름은 데이터 저장소 성능 메트릭을 볼 수 있는 선택한 데이터 저장소의 Monitor 탭으로 이동하는 링크입니다.



== 가상 시스템 보고서

Virtual Machine Report 메뉴는 선택한 vCenter Server에 대해 VSC에서 프로비저닝한 데이터 저장소를 사용하는 모든 가상 머신에 대해 다음과 같은 성능 메트릭을 제공합니다.

* 가상 머신의 이름입니다
* 약속된 용량
+
보고서에는 가상 머신에 대해 커밋된 용량 값이 표시됩니다.

* 가동 시간
+
이 보고서에는 가상 머신의 전원이 켜져 있고 ESXi 호스트에서 사용할 수 있는 시간이 표시됩니다.

* 지연 시간
+
이 보고서에는 가상 머신과 연결된 모든 데이터 저장소에서 가상 머신에 대한 지연 시간이 표시됩니다.

* 전원 상태입니다
+
이 보고서는 가상 머신의 전원이 켜져 있는지 또는 전원이 꺼져 있는지 여부를 표시합니다.

* 호스트
+
이 보고서에는 가상 머신을 사용할 수 있는 호스트 시스템이 표시됩니다.



보고서의 각 가상 머신 이름은 선택한 가상 머신의 Monitor 탭에 대한 링크입니다. 요구 사항에 따라 가상 머신 보고서를 정렬하고 보고서를 '.csv' 파일로 내보내고 보고서를 로컬 시스템에 저장할 수 있습니다. 보고서의 타임 스탬프도 저장된 보고서에 추가됩니다.
