---
permalink: manage/concept-what-vasa-provider-reports-do.html 
sidebar: sidebar 
keywords: VSC, VASA Provider, and SRA 
summary: 'VVOL 보고서는 VMware 가상 볼륨(VVol) 데이터 저장소 및 해당 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 표시합니다. VVOL 대시보드를 사용하면 vCenter Server의 VVOL 데이터 저장소 및 가상 머신에서 잠재적인 문제를 검토하고 식별할 수 있습니다.' 
---
= VVOL 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VVOL 보고서는 VMware 가상 볼륨(VVol) 데이터 저장소 및 해당 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 표시합니다. VVOL 대시보드를 사용하면 vCenter Server의 VVOL 데이터 저장소 및 가상 머신에서 잠재적인 문제를 검토하고 식별할 수 있습니다.

보고서를 보고, 구성하고, 내보낼 수 있습니다. ONTAP에서 VVOL 데이터 저장소 및 가상 머신 보고서에 대한 데이터를 OnCommand API 서비스와 함께 제공합니다.

VVOL은 사전 스캔 보고서를 다음과 같이 제공합니다.

* VVOL 데이터 저장소 보고서
* VVol VM 보고서




== VVOL 데이터 저장소 보고서

VVOL 데이터 저장소 보고서 * 메뉴는 데이터 저장소에 대한 다음 매개 변수에 대한 정보를 제공합니다.

* VVol 데이터스토어 이름입니다
* 여유 공간
* 사용된 공간
* 총 공간
* 사용된 공간의 비율입니다
* 사용 가능한 공간의 비율입니다
* IOPS
* 지연 시간


보고서가 생성된 시간을 확인할 수도 있습니다. VVol Datastore Report * (VVol 데이터스토어 보고서 *) 메뉴를 사용하면 필요에 따라 보고서를 구성한 다음 * Export to CSV * (CSV로 내보내기) 버튼을 사용하여 조직화된 보고서를 내보낼 수 있습니다. 보고서의 각 SAN VVol 데이터 저장소 이름은 선택한 SAN VVol 데이터 저장소의 * Monitor * 탭으로 이동하는 링크입니다. 이 링크를 사용하여 성능 메트릭을 볼 수 있습니다.



== VVOL 가상 머신 보고서

VVOL 가상 머신 요약 보고서 * 메뉴는 선택한 vCenter Server에 대해 VASA Provider for ONTAP가 프로비저닝한 SAN VVol 데이터 저장소를 사용하는 모든 가상 머신에 대해 다음과 같은 성능 메트릭을 제공합니다.

* 가상 머신의 이름입니다
* 약속된 용량
* 가동 시간
* 처리량
+
이 보고서는 가상 머신의 전원이 켜져 있는지 또는 전원이 꺼져 있는지 여부를 표시합니다.

* 논리적 공간입니다
* 호스트
* 전원 상태입니다
* 지연 시간
+
이 보고서는 가상 머신과 연결된 모든 VVol 데이터스토어의 가상 머신 지연 시간을 표시합니다.



보고서의 각 가상 머신 이름은 선택한 가상 머신의 * Monitor * 탭에 대한 링크입니다. 필요에 따라 가상 머신 보고서를 구성하고 보고서를 '.csv' 형식으로 내보낸 다음 보고서를 로컬 시스템에 저장할 수 있습니다. 보고서의 타임 스탬프가 저장된 보고서에 추가됩니다.
