---
permalink: manage/reference-vm-provision-fails-with-undefined-error.html 
sidebar: sidebar 
keywords: virtual, machine, provisioning, fails, with, an, undefined, error, 
summary: 생성, 클론, 전원 켜기, 전원 끄기, 일시 중단, VASA Provider 또는 VMware의 문제인지 여부를 나타내는 일반적인 오류 메시지가 작업 관리자에 표시되며, VVOL 데이터 저장소의 VM Storage Profile을 마이그레이션 및 업데이트하지 못할 수 있습니다. 
---
= 가상 시스템 프로비저닝이 정의되지 않은 오류로 실패합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
생성, 클론, 전원 켜기, 전원 끄기, 일시 중단, VASA Provider 또는 VMware의 문제인지 여부를 나타내는 일반적인 오류 메시지가 작업 관리자에 표시되며, VVOL 데이터 저장소의 VM Storage Profile을 마이그레이션 및 업데이트하지 못할 수 있습니다.



== 문제

작업 관리자에서 지정된 요구 사항에 대한 후보 볼륨 중에서 적합한 볼륨을 찾을 수 없음 등의 오류 메시지가 나타납니다



== 원인

VMware, VASA Provider 또는 ONTAP 스토리지 관련 문제로 인해 오류가 발생할 수 있습니다. 오류 메시지에 정확한 실패 이유가 지정되지 않을 수 있습니다. 이 문제는 또한 많은 수의 SVM(스토리지 가상 머신), 볼륨 및 LUN이 있는 대형 스토리지 시스템 때문일 수 있습니다. 이러한 스토리지 시스템에서 백그라운드로 실행되는 주기적 검색 작업은 시간이 오래 걸리며, 이러한 작업이 동시에 트리거되면 가상 머신 프로비저닝 작업의 시간 초과가 발생할 수 있습니다.



== 수정 조치

. /opt/netapp/vpserver/logs/error.log, vvvolvp.log 및 ZAPI_error.log 로그 파일을 검사하여 VASA Provider 또는 ONTAP 스토리지에 문제가 있는지 확인합니다.
+
** NaException com.netapp.offtap3.ontap.ApiFailedException: 같은 오류가 지정된 요구 사항에 대한 후보 볼륨 중에서 적합한 볼륨을 찾지 못한 경우 세부 정보: vVol 배치: 유형: 후보 볼륨 배치: vVol_NFS_pb2, vVol_NFS_PB1 성능: 최대 IOPS 크기: 4GB 공간 보장: 약속되지 않은 IOPS가 부족한 거짓 볼륨: vVol_NFS_PB1, vVol_NFS_pb2 결과: 성공(errno=13001)'이 보고된 경우 스토리지 관리자의 도움을 받아 스토리지 관리자가 IOPS를 높이는 등의 수정 조치를 취해야 합니다.
** 백그라운드에서 실행 중인 검색 작업이 없는 경우에만 프로비저닝 작업을 실행해야 합니다. VASA Provider 로그 파일에 보고된 오류가 구체되지 않으면 기술 지원 부서의 후속 조치를 통해 문제를 해결해야 합니다.


. VASA Provider 로그 파일에 특정 오류가 보고되지 않으면 'sps.log' 로그 파일을 검토하여 VMware에 문제가 있는지 확인한 다음 보고된 오류에 따라 적절한 수정 조치를 취합니다.
+
'ps.log' 로그 파일에 보고된 오류가 구체화되지 않으면 VMware 관리자에게 문의하여 문제를 해결해야 합니다.


