---
permalink: manage/reference-considerations-for-migrating-virtual-machines.html 
sidebar: sidebar 
keywords: considerations, for, migrating, or, cloning, virtual, machines, 
summary: 데이터 센터에서 가상 시스템을 마이그레이션하는 동안 고려해야 할 몇 가지 사항에 대해 알고 있어야 합니다. 
---
= 가상 머신의 마이그레이션 또는 클론 생성 시 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 센터에서 가상 시스템을 마이그레이션하는 동안 고려해야 할 몇 가지 사항에 대해 알고 있어야 합니다.



== 보호된 가상 시스템을 마이그레이션합니다

보호된 가상 시스템을 다음으로 마이그레이션할 수 있습니다.

* 다른 ESXi 호스트에서 동일한 VVol 데이터 저장소
* 동일한 ESXi 호스트에서 서로 다른 호환되는 VVol 데이터 저장소
* 다른 ESXi 호스트에서 서로 다른 호환되는 VVol 데이터 저장소


가상 머신이 다른 FlexVol 볼륨으로 마이그레이션되면 해당 메타데이터 파일도 가상 머신 정보로 업데이트됩니다. 가상 머신이 다른 ESXi 호스트로 마이그레이션되지만 동일한 스토리지로 마이그레이션되는 경우 기본 FlexVol 볼륨 메타파일이 수정되지 않습니다.



== 보호된 가상 머신의 클론을 생성합니다

보호된 가상 컴퓨터를 다음 컴퓨터에 클론 복제할 수 있습니다.

* 복제 그룹을 사용하는 동일한 FlexVol 볼륨의 동일한 컨테이너입니다
+
동일한 FlexVol 볼륨의 메타데이터 파일이 클론 복제된 가상 머신 세부 정보로 업데이트됩니다.

* 복제 그룹을 사용하는 다른 FlexVol 볼륨의 동일한 컨테이너입니다
+
클론 생성된 가상 머신이 배치되는 FlexVol 볼륨에서는 메타데이터 파일이 클론 생성된 가상 머신 세부 정보로 업데이트됩니다.

* 컨테이너 또는 VVOL 데이터 저장소가 서로 다릅니다
+
클론 생성된 가상 머신이 배치되는 FlexVol 볼륨에서는 메타데이터 파일이 업데이트된 가상 머신 세부 정보를 가져옵니다.



현재 VMware는 VM 템플릿에 복제된 가상 시스템을 지원하지 않습니다.

보호된 가상 머신의 클론 복제가 지원됩니다.



== 가상 머신 스냅샷

현재 메모리가 없는 가상 머신 스냅샷만 지원됩니다. 가상 머신에 메모리가 있는 스냅샷이 있는 경우 가상 머신이 보호 대상으로 고려되지 않습니다.

메모리 스냅샷이 있는 보호되지 않는 가상 머신도 보호할 수 없습니다. 이 릴리즈에서는 가상 머신에 대한 보호를 활성화하기 전에 메모리 스냅샷을 삭제해야 합니다.
