---
permalink: manage/reference-verify-vvol-dashboard-data-requirements.html 
sidebar: sidebar 
keywords: vVol, dashboard, data, requirements, 
summary: 'VVOL(VMware 가상 볼륨) 데이터 저장소 및 가상 시스템의 동적 세부 정보를 표시하려면 VVOL 대시보드의 몇 가지 중요한 요구사항을 확인해야 합니다.' 
---
= VVOL 대시보드 데이터 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VVOL(VMware 가상 볼륨) 데이터 저장소 및 가상 시스템의 동적 세부 정보를 표시하려면 VVOL 대시보드의 몇 가지 중요한 요구사항을 확인해야 합니다.

다음 표에는 VVOL 대시보드가 프로비저닝된 SAN VVol 데이터 저장소 및 가상 머신에 대한 성능 메트릭을 표시하지 않을 경우 확인해야 할 사항에 대한 개요가 나와 있습니다.

[cols="1a,1a"]
|===
| 고려 사항 | 설명 


 a| 
OnCommand API Services를 처음 구축하는 경우
 a| 
* ONTAP 클러스터 9.6 이하가 있는 경우 OnCommand API 서비스 2.1 이상을 사용하고 있는 것입니다.
+
ONTAP 9.7 이상을 사용하는 경우 VASA Provider에 OnCommand API Services를 등록할 필요가 없습니다.

* NetApp Support 사이트에서 OnCommand API Services를 다운로드 및 설치한 후_OnCommand API 서비스 설치 및 설정 가이드에 제공된 설치 지침을 따라야 합니다.
* 각 VASA 공급자 인스턴스에는 전용 OnCommand API 서비스 인스턴스가 있어야 합니다.
+
OnCommand API 서비스는 여러 VASA 공급자 인스턴스 또는 vCenter Server 간에 공유해서는 안 됩니다.

* OnCommand API 서비스가 실행되고 있으며 액세스할 수 있습니다.




 a| 
수행할 수 있습니다
 a| 
* ONTAP 9.3 이상을 사용하고 있습니다.
* 스토리지 시스템에 적합한 자격 증명을 사용하고 있습니다.
* 스토리지 시스템이 활성 상태이며 액세스할 수 있습니다.
* 선택한 가상 머신에서 하나 이상의 VVol 데이터 저장소를 사용해야 하며, 가상 머신의 디스크에서 I/O 작업이 실행되고 있어야 합니다.


|===