---
permalink: manage/task-migrate-existing-virtual-machines-to-7-1-virtual-appliance.html 
sidebar: sidebar 
keywords: migrating, virtual, machines, with, older, storage, capability, profiles, 
summary: '가상 스토리지 콘솔(VSC), VASA 공급자, SRA(스토리지 복제 어댑터)용 가상 어플라이언스의 최신 버전을 사용하는 경우, 그런 다음 "MaxThroughput Mbps" 또는 "MaxThroughput IOPS" QoS 메트릭으로 프로비저닝된 가상 머신을 VSC, VASA Provider 및 SRA용 가상 어플라이언스의 최신 버전의 "Max IOPS" QoS 메트릭을 통해 프로비저닝된 새로운 VVOL 데이터 저장소로 마이그레이션해야 합니다.' 
---
= 이전 스토리지 기능 프로파일이 있는 가상 시스템을 마이그레이션합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 스토리지 콘솔(VSC), VASA 공급자, SRA(스토리지 복제 어댑터)용 가상 어플라이언스의 최신 버전을 사용하는 경우, 그런 다음 " MaxThroughput Mbps" 또는 " MaxThroughput IOPS" QoS 메트릭으로 프로비저닝된 가상 머신을 VSC, VASA Provider 및 SRA용 가상 어플라이언스의 최신 버전의 " max IOPS " QoS 메트릭으로 프로비저닝된 새 VVOL 데이터 저장소로 마이그레이션해야 합니다.

VSC, VASA Provider, SRA를 위한 최신 버전의 가상 어플라이언스를 사용하면 각 가상 머신 또는 가상 머신 디스크(VMDK)에 대한 QoS 메트릭을 구성할 수 있습니다. QoS 메트릭은 이전에 ONTAP FlexVol 볼륨 레벨에 적용되었으며 해당 FlexVol 볼륨에 프로비저닝된 모든 가상 머신 또는 VMDK에서 공유되었습니다.

VSC, VASA Provider, SRA를 위한 가상 어플라이언스의 7.2 버전부터 한 가상 시스템의 QoS 메트릭은 다른 가상 시스템과 공유되지 않습니다.

[NOTE]
====
가상 머신이 규정을 준수하지 않을 수 있으므로 기존 VM 스토리지 정책을 수정하지 않아야 합니다.

====
.단계
. 필요한 " Max IOPS " 값이 포함된 새 스토리지 기능 프로필을 사용하여 VVOL 데이터 저장소를 생성합니다.
. VM 스토리지 정책을 생성한 다음 새 VM 스토리지 정책을 새 스토리지 용량 프로필과 매핑합니다.
. 새로운 VM Storage Policy를 사용하여 기존 가상 머신을 새로 생성한 VVOL 데이터 저장소로 마이그레이션합니다.

