---
permalink: manage/task-monitor-vvols-datastores-and-virtual-machines-using-vvols-dashboard.html 
sidebar: sidebar 
keywords: monitoring, vvols, datastores, virtual, machines, using, the, vVol, dashboard, 
summary: 'VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)를 위해 가상 어플라이언스의 VVol 대시보드를 사용하여 선택한 매개 변수를 기준으로 vCenter Server에서 성능을 모니터링하고 상위 5개 SAN VVol(VMware Virtual Volumes) 데이터 저장소를 볼 수 있습니다.' 
---
= VVOL 대시보드를 사용하여 VVOL 데이터 저장소 및 가상 머신을 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)를 위해 가상 어플라이언스의 VVol 대시보드를 사용하여 선택한 매개 변수를 기준으로 vCenter Server에서 성능을 모니터링하고 상위 5개 SAN VVol(VMware Virtual Volumes) 데이터 저장소를 볼 수 있습니다.

.시작하기 전에
* ONTAP 9.6 이하를 사용하는 경우 OnCommand API 서비스 2.1 이상을 활성화해야 합니다.
+
ONTAP 9.7용 SAN VVol 데이터 저장소 또는 SAN VVol VM 데이터 저장소 보고서의 세부 정보를 얻기 위해 VASA Provider에 OnCommand API Services를 등록할 필요는 없습니다.

+
https://mysupport.netapp.com/site/["NetApp 지원"^]

* 스토리지 시스템에 ONTAP 9.3 이상을 사용해야 합니다.


link:reference-verify-vvol-dashboard-data-requirements.html["VVOL 대시보드 데이터 요구사항"]

.이 작업에 대해
ONTAP에서 제공하는 IOPS 데이터는 반올림되어 VVOL 대시보드에 표시됩니다. ONTAP에서 제공하는 실제 IOPS 값과 VVOL 대시보드에 표시되는 IOPS 값이 다를 수 있습니다.

[NOTE]
====
* OnCommand API Services를 처음으로 등록하는 경우, VVOL 대시보드에서 SAN VVOL 데이터 저장소의 모든 성능 메트릭 데이터를 15~30분 후에만 볼 수 있습니다.
* VVOL 대시보드 데이터는 10분 간격으로 주기적으로 업데이트됩니다.
* vCenter Server 인스턴스에서 스토리지 시스템을 추가, 수정 또는 삭제한 경우, 일정 기간 동안 VVol 대시보드의 데이터가 변경되지 않을 수 있습니다.
+
이는 OnCommand API 서비스가 ONTAP에서 업데이트된 메트릭을 얻는 데 시간이 오래 걸리기 때문입니다.

* VVol 대시보드의 * Overview * 포틀릿에 표시되는 총 IOPS 값은 Read IOPS 값과 Write IOPS 값의 누적 값이 아닙니다.
+
읽기 IOPS, 쓰기 IOPS, 총 IOPS는 OnCommand API 서비스에서 제공하는 별도의 메트릭입니다. OnCommand API Services에서 제공하는 총 IOPS 값과 누적 IOPS 값(읽기 IOPS 값 + 쓰기 IOPS 값)이 서로 다른 경우, VVOL 대시보드의 IOPS 값에서도 동일한 차이가 관찰됩니다.



====
.단계
. vSphere Client 홈 페이지에서 * Virtual Storage Console * 을 클릭합니다.
. vCenter Server * 드롭다운 메뉴를 사용하여 필요한 vCenter Server를 선택하여 데이터 저장소를 표시합니다.
. VVOL 대시보드 * 를 클릭합니다.
+
Datastores * 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server 인스턴스에서 VASA Provider가 관리하는 VVol 데이터 저장소의 수입니다
** 리소스 사용량 및 성능 매개 변수를 기준으로 상위 5개의 VVOL 데이터 저장소 활용 공간, IOPS 또는 지연 시간과 필요한 순서에 따라 데이터 저장소 목록을 변경할 수 있습니다.


. 가상 머신 * 포틀릿을 사용하여 가상 머신의 세부 정보를 봅니다.
+
가상 머신 * 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server에서 ONTAP 데이터 저장소를 사용하는 가상 머신의 수입니다
** IOPS, 지연 시간, 처리량, 약정 용량, 가동 시간, 및 논리 공간 - VVOL 대시보드에 상위 5개 가상 시스템이 나열되는 방식을 사용자 지정할 수 있습니다.



