---
permalink: manage/task-provision-datastores.html 
sidebar: sidebar 
keywords: provisioning, datastores, 
summary: '데이터 저장소를 프로비저닝하면 가상 머신 및 해당 VMDK(가상 머신 디스크)에 대한 논리적 컨테이너가 생성됩니다. 데이터 저장소를 프로비저닝한 다음 데이터 저장소를 단일 호스트, 클러스터의 모든 호스트 또는 데이터 센터의 모든 호스트에 연결할 수 있습니다.' 
---
= 데이터 저장소를 프로비저닝합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 저장소를 프로비저닝하면 가상 머신 및 해당 VMDK(가상 머신 디스크)에 대한 논리적 컨테이너가 생성됩니다. 데이터 저장소를 프로비저닝한 다음 데이터 저장소를 단일 호스트, 클러스터의 모든 호스트 또는 데이터 센터의 모든 호스트에 연결할 수 있습니다.

.시작하기 전에
* VSC(가상 스토리지 콘솔)에 직접 연결된 SVM에서 데이터 저장소를 프로비저닝하려면 기본 vsadmin 사용자 계정 또는 vsadmin 역할이 아닌 적절한 권한이 있는 사용자 계정을 사용하여 SVM을 VSC에 추가해야 합니다.
+
클러스터를 추가하여 데이터 저장소를 프로비저닝할 수도 있습니다.

* ESXi가 호스팅하는 모든 네트워크의 서브넷 세부 정보가 kaminoprefs.xml에 입력되어 있는지 확인해야 합니다.
+
VSC 9.6 구축 및 설정 가이드 _ 의 "다른 서브넷에 대한 데이터 저장소 마운트 활성화" 섹션을 참조하십시오.

* NFS 또는 iSCSI를 사용하는 경우 서브넷이 ESXi 호스트와 스토리지 시스템 간에 다르면 "kaminoprefs" 기본 설정 파일의 NFS 또는 iSCSI 설정에는 ESXi 호스트 서브넷 마스크가 포함되어야 합니다.
+
이 기본 설정 파일은 VVOL 데이터 저장소 생성에도 적용할 수 있습니다. _9.6 릴리즈에 대한 Virtual Storage Console, VASA Provider 및 Storage Replication Adapter Deployment and Setup Guide는 기본 설정 파일 및 서로 다른 서브넷에서의 데이터 저장소 마운트 설정에 대한 자세한 정보를 제공합니다.

* VASA Provider를 설정하고 NFS 데이터 저장소 또는 VMFS 데이터 저장소에 대한 스토리지 용량 프로필을 지정하려면 하나 이상의 스토리지 기능 프로필을 생성해야 합니다.
* NFSv4.1 데이터 저장소를 생성하려면 SVM 레벨에서 NFSv4.1을 설정해야 합니다.


Provision Datastore * 옵션을 사용하면 데이터 저장소에 대한 스토리지 용량 프로필을 지정할 수 있습니다. 스토리지 기능 프로필을 통해 일관된 서비스 수준 목표(SLO)를 지정하고 프로비저닝 프로세스를 간소화할 수 있습니다. VASA Provider를 설정한 경우에만 스토리지 용량 프로파일을 지정할 수 있습니다. VSC, VASA Provider 및 SRA를 위한 가상 어플라이언스는 다음 프로토콜을 지원합니다.

* NFSv3과 NFSv4.1
* VMFS5 및 VMFS6


VSC는 NFS 볼륨 또는 LUN에 데이터 저장소를 생성할 수 있습니다.

* NFS 데이터 저장소의 경우 VSC는 스토리지 시스템에 NFS 볼륨을 생성한 다음 엑스포트 정책을 업데이트합니다.
* VMFS 데이터 저장소의 경우 VSC는 새 볼륨을 생성한(또는 옵션을 선택한 경우 기존 볼륨 사용) LUN 및 igroup을 생성합니다.


[NOTE]
====
VMware는 데이터 저장소 클러스터가 포함된 NFSv4.1을 지원하지 않습니다.

====
용량 할당 중에 스토리지 용량 프로필을 지정하지 않은 경우 나중에 스토리지 매핑 페이지를 사용하여 데이터 저장소를 스토리지 용량 프로필에 매핑할 수 있습니다.

.단계
. 다음 중 하나를 사용하여 데이터 저장소 프로비저닝 마법사를 액세스할 수 있습니다.
+
[cols="1a,1a"]
|===
| 다음 중에서 선택할 경우... | 다음을 수행합니다. 


 a| 
* vSphere Client 홈 페이지 *
 a| 
.. 호스트 및 클러스터 * 를 클릭합니다.
.. 탐색 창에서 데이터 저장소를 프로비저닝할 데이터 센터를 선택합니다.
.. 데이터 저장소를 마운트할 호스트를 지정하려면 다음 단계를 참조하십시오.




 a| 
* Virtual Storage Console 홈 페이지 *
 a| 
.. 개요 * 를 클릭합니다.
.. * 시작하기 * 탭을 클릭합니다.
.. Provision * 버튼을 클릭합니다.
.. 찾아보기 * 를 클릭하여 다음 단계에 따라 데이터 저장소를 프로비저닝할 대상을 선택합니다.


|===
. 데이터 저장소를 마운트할 호스트를 지정합니다.
+
[cols="1a,1a"]
|===
| 데이터 저장소를 사용할 수 있는 대상 | 수행할 작업... 


 a| 
데이터 센터에 있는 모든 호스트
 a| 
데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 NetApp VSC [Provision Datastore] 메뉴를 선택합니다.



 a| 
클러스터의 모든 호스트
 a| 
호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 menu:NetApp VSC [Provision Datastore] 를 선택합니다.



 a| 
단일 호스트
 a| 
호스트를 마우스 오른쪽 버튼으로 클릭하고 NetApp VSC [Provision Datastore] 메뉴를 선택합니다.

|===
. New Datastore * 대화 상자의 필드를 입력하여 데이터 저장소를 생성합니다.
+
대화 상자의 대부분의 필드는 설명이 필요 없습니다. 다음 표에서는 안내가 필요할 수 있는 일부 필드에 대해 설명합니다.

+
[cols="1a,1a"]
|===
| 섹션을 참조하십시오 | 설명 


 a| 
일반
 a| 
New Datastore provisioning * 대화 상자의 * General * 섹션에서는 새 데이터 저장소의 대상, 이름, 크기, 유형 및 프로토콜을 입력하는 옵션을 제공합니다. NFS * 또는 * VMFS * 프로토콜을 선택하여 기존 데이터 저장소를 구성할 수 있습니다. VVOL 데이터 저장소 유형은 VVol 데이터 저장소를 구성하는 데 사용됩니다. VASA Provider가 설정된 경우 스토리지 용량 프로필을 사용할지 여부를 결정할 수도 있습니다. Datastore cluster * 옵션은 기존 데이터 저장소에만 사용할 수 있습니다. 고급 * 옵션을 사용하여 * VMFS5 * 또는 * VMFS6 * 파일 시스템을 지정해야 합니다.



 a| 
수행할 수 있습니다
 a| 
일반 * 섹션에서 옵션을 선택한 경우 나열된 스토리지 용량 프로파일 중 하나를 선택할 수 있습니다. 스토리지 시스템 및 스토리지 가상 머신에 대해 시스템 권장 값이 자동으로 채워지는 것이 좋습니다. 그러나 필요한 경우 값을 수정할 수 있습니다.



 a| 
스토리지 특성
 a| 
기본적으로 VSC는 * 애그리게이트 * 및 * 볼륨 * 옵션의 권장 값을 채웁니다. 요구 사항에 따라 값을 사용자 지정할 수 있습니다. 고급* 메뉴에서 사용할 수 있는 * 공간 예약 * 옵션도 채워지며 최적의 결과를 제공합니다.



 a| 
요약
 a| 
새 데이터 저장소에 대해 지정한 매개 변수의 요약을 검토할 수 있습니다.

|===
. 요약 * 섹션에서 * 마침 * 을 클릭합니다.

