---
permalink: manage/task-provision-vvol-datastores.html 
sidebar: sidebar 
keywords: provisioning, vvols, datastores, 
summary: VSC, VASA Provider 및 SRA를 위해 가상 어플라이언스에서 VASA Provider가 활성화된 경우에만 데이터 저장소 프로비저닝 마법사를 사용하여 VVOL 데이터 저장소를 프로비저닝할 수 있습니다. 
---
= VVOL 데이터 저장소를 프로비저닝합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VSC, VASA Provider 및 SRA를 위해 가상 어플라이언스에서 VASA Provider가 활성화된 경우에만 * Provision Datastore * 마법사를 사용하여 VVol 데이터 저장소를 프로비저닝할 수 있습니다.

.시작하기 전에
* ESXi가 호스팅하는 모든 네트워크의 서브넷 세부 정보가 'Kaminoprefs.xml'에 입력되어 있는지 확인해야 합니다.
+
VSC 9.7 구축 및 설정 가이드 _ 의 * 서로 다른 서브넷에 대한 데이터 저장소 마운트 활성화 * 섹션을 참조하십시오.

* 역방향 복제가 성공하려면 소스 사이트와 타겟 사이트 모두에서 데이터 저장소에 유사한 복제 정책 및 스케줄을 구성해야 합니다.


.이 작업에 대해
Provision DataStore * 메뉴를 사용하면 데이터 저장소에 대한 스토리지 기능 프로필을 지정할 수 있으므로 일관된 SLO(서비스 수준 목표)를 지정하고 프로비저닝 프로세스를 간소화할 수 있습니다. VASA Provider를 설정한 경우에만 스토리지 용량 프로파일을 지정할 수 있습니다.

백업 스토리지로 사용되는 FlexVol 볼륨은 ONTAP 9.5 이상을 실행 중인 경우에만 VVOL 대시보드에 표시됩니다. vCenter Server * New Datastore * 마법사를 사용하여 VVOL 데이터 저장소를 프로비저닝해서는 안 됩니다.

* VVOL 데이터 저장소를 생성하려면 클러스터 자격 증명을 사용해야 합니다.
+
SVM 자격 증명을 사용하여 VVol 데이터 저장소를 생성할 수 없습니다.

* VASA Provider는 프로토콜의 VVol 데이터 저장소에서 다른 프로토콜을 사용하는 다른 데이터 저장소로 호스팅되는 가상 머신의 클론을 지원하지 않습니다.
* 소스 사이트와 대상 사이트 모두에서 클러스터 페어링 및 SVM 페어링을 완료해야 합니다.


.단계
. vSphere Client 홈 페이지에서 * 호스트 및 클러스터 * 를 클릭합니다.
. 탐색 창에서 데이터 저장소를 프로비저닝할 데이터 센터를 선택합니다.
. 데이터 저장소를 마운트할 호스트를 지정합니다.
+
[cols="1a,1a"]
|===
| 데이터 저장소를 사용할 수 있는 대상 | 수행할 작업... 


 a| 
데이터 센터에 있는 모든 호스트
 a| 
데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 NetApp VSC [Provision Datastore] 메뉴를 선택합니다.



 a| 
클러스터의 모든 호스트
 a| 
클러스터를 마우스 오른쪽 버튼으로 클릭하고 NetApp VSC [Provision Datastore] 메뉴를 선택합니다.



 a| 
단일 호스트
 a| 
호스트를 마우스 오른쪽 버튼으로 클릭한 후 menu:NetApp VSC [Provision Datastore] 를 선택합니다.

|===
. New Datastore * 대화 상자의 필드를 입력하여 데이터 저장소를 생성합니다.
+
대화 상자의 대부분의 필드는 설명이 필요 없습니다. 다음 표에서는 안내가 필요할 수 있는 일부 필드에 대해 설명합니다.

+
[cols="1a,1a"]
|===
| 섹션을 참조하십시오 | 설명 


 a| 
일반
 a| 
New Datastore * 대화 상자의 * General * 섹션에서는 새 데이터 저장소의 위치, 이름, 설명, 유형 및 프로토콜을 입력하는 옵션을 제공합니다. VVOL 데이터 저장소 유형은 VVol 데이터 저장소를 구성하는 데 사용됩니다.

[NOTE]
====
VVOL 복제를 위해 iSCSI VVOL 데이터 저장소를 프로비저닝하고 타겟 사이트에서 VVol 데이터 저장소를 생성하기 전에 SnapMirror 업데이트 및 클러스터 재검색을 수행해야 합니다.

====


 a| 
수행할 수 있습니다
 a| 
이 섹션에서는 VVOL 데이터 저장소에 복제를 활성화할지 또는 비활성화할지를 선택할 수 있습니다. 이 릴리즈에서는 비동기 유형 복제 프로파일만 허용됩니다. 그런 다음 나열된 스토리지 용량 프로필을 하나 이상 선택할 수 있습니다. 페어링된 * 스토리지 시스템 * 및 * 스토리지 VM * 의 시스템 권장 값이 자동으로 채워집니다. 권장 값은 ONTAP에서 페어링된 경우에만 채워집니다. 필요한 경우 이러한 값을 수정할 수 있습니다.

[NOTE]
====
ONTAP에서 FlexVol 볼륨을 생성하는 동안 스토리지 용량 프로필에서 선택할 속성을 사용하여 볼륨을 생성해야 합니다. 읽기 쓰기 및 데이터 보호 FlexVol 볼륨은 모두 유사한 특성을 가져야 합니다.

====
FlexVol 볼륨이 생성되고 ONTAP에서 SnapMirror를 초기화한 후에는 VSC에서 스토리지 재검색을 실행하여 새 볼륨을 볼 수 있어야 합니다.



 a| 
스토리지 특성
 a| 
기존 목록에서 SnapMirror와 필요한 FlexVol 볼륨의 일정을 선택해야 합니다. 이 스케줄은 VM 스토리지 정책 페이지에서 선택한 스케줄과 비슷해야 합니다. 사용자는 목록에 있는 SnapMirror와 함께 ONTAP에 FlexVol 볼륨을 생성해야 합니다. Default storage capability profile * 옵션을 사용하여 VVol 생성에 사용할 기본 저장소 기능 프로파일을 선택할 수 있습니다.

|===
. 요약 * 섹션에서 * 마침 * 을 클릭합니다.
+
VVol 데이터 저장소가 구성되면 백엔드에서 복제 그룹이 생성됩니다.



* 관련 정보 *

xref:reference-verify-vvol-dashboard-data-requirements.adoc[VVOL 대시보드 데이터 요구사항]
