---
permalink: manage/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, for, storage, systems, 
summary: VMware vSphere용 Virtual Storage Console을 사용하여 vCenter Server의 스토리지 시스템에 대한 기본 자격 증명을 설정할 수 있습니다. 
---
= 스토리지 시스템에 대한 기본 자격 증명을 설정합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 Virtual Storage Console을 사용하여 vCenter Server의 스토리지 시스템에 대한 기본 자격 증명을 설정할 수 있습니다.

.시작하기 전에
기본 자격 증명을 생성하는 데 사용할 vCenter Server를 선택해야 합니다.

.이 작업에 대해
스토리지 시스템에 대한 기본 자격 증명을 설정하면 VSC(가상 스토리지 콘솔)에서 이러한 자격 증명을 사용하여 VSC가 방금 검색한 스토리지 시스템에 로그인합니다. 기본 자격 증명이 작동하지 않는 경우 스토리지 시스템에 수동으로 로그인해야 합니다. VSC 및 SRA는 클러스터 수준 또는 SVM 수준에서 스토리지 시스템 자격 증명의 추가를 지원합니다. 그러나 VASA Provider는 클러스터 레벨 자격 증명에서만 작동합니다.

.단계
. VSC * Home * 페이지에서 설정 [관리 설정 > 스토리지 시스템의 기본 자격 증명 구성] 메뉴를 클릭합니다.
. 스토리지 시스템 기본 자격 증명 * 대화 상자에서 스토리지 시스템의 사용자 이름과 암호를 입력합니다.
+
스토리지 컨트롤러 자격 증명은 사용자 이름 및 암호 쌍에 따라 ONTAP에 할당됩니다. 스토리지 컨트롤러 자격 증명은 관리자 계정 또는 RBAC(역할 기반 액세스 제어)를 사용하는 사용자 지정 계정일 수 있습니다.

+
VSC를 사용하여 스토리지 컨트롤러의 사용자 이름 및 암호 쌍과 관련된 역할을 변경할 수는 없습니다. VSC, VASA 공급자, SRA를 위한 가상 어플라이언스에 사용할 새 ONTAP 사용자 역할을 수정하거나 새로 생성할 수 있습니다. System Manager를 사용할 수 있습니다.

+
9.7 Release_용 _Virtual Storage Console, VASA Provider, Storage Replication Adapter for VMware ® vSphere Deployment and Setup Guide의 ""사용자 역할 및 권한 구성" 섹션을 참조하십시오.

. 기본 자격 증명을 저장하려면 * 확인 * 을 클릭합니다.


.작업을 마친 후
스토리지 시스템에서 ""인증 실패" 상태를 보고하여 스토리지 시스템 자격 증명을 업데이트한 경우 * 스토리지 시스템 * 페이지에서 사용할 수 있는 * 모두 다시 검색 * 옵션을 클릭해야 합니다. 이렇게 하면 VSC에서 새 자격 증명을 사용하여 스토리지 시스템에 연결하려고 시도합니다.
