---
permalink: manage/task-monitor-datastores-using-the-traditional-dashboard.html 
sidebar: sidebar 
keywords: monitoring, datastores, virtual, machines, using, the, traditional, dashboard, 
summary: Virtual Storage Console, VASA Provider 및 Storage Replication Adapter에 대한 가상 어플라이언스의 기존 대시보드를 사용하여 기존 데이터 저장소와 가상 머신을 모니터링할 수 있습니다. 대시보드 데이터를 사용하여 데이터 저장소 사용량을 분석하고 수정 조치를 취하여 가상 머신이 공간 관련 제약으로 실행되지 않도록 방지할 수 있습니다. 
---
= 기존 대시보드를 사용하여 데이터 저장소와 가상 머신을 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console, VASA Provider 및 Storage Replication Adapter에 대한 가상 어플라이언스의 기존 대시보드를 사용하여 기존 데이터 저장소와 가상 머신을 모니터링할 수 있습니다. 대시보드 데이터를 사용하여 데이터 저장소 사용량을 분석하고 수정 조치를 취하여 가상 머신이 공간 관련 제약으로 실행되지 않도록 방지할 수 있습니다.

.시작하기 전에
스토리지 I/O 제어 구성 대화 상자에서 * 스토리지 I/O 제어 활성화 및 통계 수집 * 또는 * 스토리지 I/O 제어 비활성화를 선택해야 하지만 통계 수집 * 옵션을 활성화해야 합니다. VMware의 Enterprise Plus 라이센스가 있는 경우에만 스토리지 I/O 제어를 활성화할 수 있습니다.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-BB5D9BAB-9E0E-4204-A76A-54634CD8AD51.html["VMware vSphere 설명서: 스토리지 입출력 제어 설정"^]

.이 작업에 대해
VSC 대시보드에는 vCenter Server에서 얻은 IOPS, 공간 활용, 지연 시간, 약정 용량 메트릭이 표시됩니다. ONTAP는 VSC 대시보드에 볼륨 공간 절약 메트릭을 제공합니다. 이러한 성능 매개 변수를 사용하여 가상 환경의 성능 병목 현상을 파악하고 수정 조치를 취하여 문제를 해결할 수 있습니다.

VSC, VASA Provider, SRA를 위한 가상 어플라이언스의 기존 대시보드를 사용하면 NFS 데이터 저장소나 VMFS 데이터 저장소를 볼 수 있습니다. 데이터 저장소를 클릭하여 vCenter Server 인스턴스에서 제공하는 데이터 저장소 세부 정보 보기로 이동하여 vCenter Server의 데이터 저장소 문제를 확인하고 해결할 수 있습니다.

.단계
. vSphere Client 홈 페이지에서 * Virtual Storage Console * 을 클릭합니다.
. vCenter Server * 드롭다운 메뉴를 사용하여 필요한 vCenter Server를 선택하여 데이터 저장소를 표시합니다.
. 기존 대시보드 * 를 클릭합니다.
+
Datastores * 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server 인스턴스에서 VSC에 의해 관리되는 성능 메트릭과 함께 기존 데이터 저장소의 수
** 수정할 수 있는 리소스 사용 및 성능 매개 변수를 기준으로 상위 5개 데이터 저장소 필요 시 사용된 공간, IOPS 또는 지연 시간과 필요한 순서대로 데이터 저장소 목록을 변경할 수 있습니다.


+
가상 머신 * 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server에서 NetApp 데이터 저장소를 사용하는 가상 머신의 수입니다
** 커밋된 용량, 지연 시간 및 가동 시간을 기반으로 한 상위 5개의 가상 머신



