---
permalink: manage/task-map-storage-to-storage-capability-profiles.html 
sidebar: sidebar 
keywords: mapping, datastores, to, storage, capability, profiles, 
summary: VASA Provider for ONTAP와 연결된 데이터 저장소를 스토리지 기능 프로필에 매핑할 수 있습니다. 스토리지 용량 프로필과 연결되지 않은 데이터 저장소에 프로필을 할당할 수 있습니다. 
---
= 스토리지 용량 프로필에 데이터 저장소를 매핑합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP와 연결된 데이터 저장소를 스토리지 기능 프로필에 매핑할 수 있습니다. 스토리지 용량 프로필과 연결되지 않은 데이터 저장소에 프로필을 할당할 수 있습니다.

.시작하기 전에
* VMware vSphere용 Virtual Storage Console을 사용하여 VASA Provider 인스턴스를 등록해야 합니다.
* VSC(가상 스토리지 콘솔)에서 스토리지를 이미 검색했을 것입니다.


.이 작업에 대해
기존 데이터 저장소를 스토리지 용량 프로필과 매핑하거나 데이터 저장소와 연결된 스토리지 용량 프로필을 변경할 수 있습니다. VASA Provider는 * Storage Mappings * 페이지에 가상 볼륨(VVol) 데이터 저장소를 _ 표시_하지 않습니다. 이 작업에서 참조하는 모든 데이터 저장소는 기존 데이터 저장소입니다.

.단계
. VSC * 홈 * 페이지에서 * 스토리지 매핑 * 을 클릭합니다.
+
Storage Mapping * 페이지에서 다음 정보를 확인할 수 있습니다.

+
** 데이터 저장소와 연결된 vCenter Server입니다
** 데이터 저장소와 일치하는 프로파일 수
+
Storage Mapping * 페이지에는 기존 데이터 저장소만 표시됩니다. 이 페이지에는 VVOL 데이터 저장소 또는 qtree 데이터 저장소가 표시되지 않습니다.

** 데이터 저장소가 현재 프로파일과 연결되어 있는지 여부
+
데이터 저장소는 여러 프로파일을 일치시킬 수 있지만 데이터 저장소는 하나의 프로파일에만 연결될 수 있습니다.

** 데이터 저장소가 연결된 프로파일을 준수하는지 여부


. 스토리지 용량 프로파일을 데이터 저장소에 매핑하거나 데이터 저장소의 기존 프로파일을 변경하려면 데이터 저장소를 선택합니다.
+
스토리지 매핑 * 페이지에서 특정 데이터 저장소나 기타 정보를 찾으려면 검색 상자에 이름이나 부분 문자열을 입력합니다. VSC 대화 상자에 검색 결과가 표시됩니다. 전체 화면으로 돌아가려면 검색 상자에서 텍스트를 제거한 다음 * Enter * 를 클릭합니다.

. Actions * 메뉴에서 * Assign Matching Profile * 을 선택합니다.
. 데이터 저장소에 매핑할 프로파일을 * 데이터 저장소에 할당 * 대화 상자에 제공된 일치하는 프로파일 목록에서 선택한 다음 * 확인 * 을 클릭하여 선택한 프로파일을 데이터 저장소에 매핑합니다.
. 화면을 새로 고쳐 새 할당을 확인합니다.

