---
permalink: manage/task-add-storage-to-a-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual, volume, datastores, adding, storage, to, a, vVols, datastore, 
summary: '스토리지 추가 마법사를 사용하여 FlexVol 볼륨을 기존 VVol(VMware 가상 볼륨) 데이터 저장소에 추가하여 사용 가능한 스토리지를 늘릴 수 있습니다.' 
---
= VVOL 데이터 저장소에 스토리지를 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 추가 * 마법사를 사용하여 FlexVol 볼륨을 기존 VVol(VMware 가상 볼륨) 데이터 저장소에 추가하여 사용 가능한 스토리지를 늘릴 수 있습니다.

.이 작업에 대해
FlexVol 볼륨을 추가할 때 해당 볼륨과 연결된 스토리지 용량 프로필을 변경할 수도 있습니다. VASA Provider 자동 생성 기능을 사용하여 볼륨에 대한 새 프로파일을 만들거나 기존 프로파일 중 하나를 볼륨에 할당할 수 있습니다.

[NOTE]
====
* 복제 기능을 사용하여 VVOL 데이터 저장소를 확장하는 동안 새 FlexVol 볼륨을 생성할 수 없지만 기존 목록에서 사전 구성된 FlexVol 볼륨만 선택할 수 있습니다.
* 공간 부족으로 인해 VVOL 복제를 통해 데이터 저장소에 구축된 보호된 가상 머신을 클론 복제하지 못할 경우 FlexVol 볼륨 크기를 늘려야 합니다.
* AFF 클러스터에서 VVOL 데이터 저장소를 생성하는 경우 스토리지 기능 프로필을 자동으로 생성하는 다른 FlexVol 볼륨으로 데이터 저장소를 확장할 수 없습니다.
+
스토리지 기능 프로필이 사전 생성된 FlexVol 볼륨으로 VVOL 데이터 저장소를 확장할 수 있습니다.



====
.단계
. vSphere Client * Home * 페이지에서 * 호스트 및 클러스터 * 를 클릭합니다.
. VVOL 데이터 저장소를 마우스 오른쪽 버튼으로 클릭한 후 NetApp VSC [VVOL 데이터 저장소의 스토리지 확장]을 선택합니다.
. VVOL 데이터 저장소의 * 스토리지 확장 * 페이지에서 기존 FlexVol 볼륨을 VVol 데이터 저장소에 추가하거나 데이터베이스에 추가할 새 FlexVol 볼륨을 생성할 수 있습니다.
+
[cols="1a,1a"]
|===
| 다음을 선택한 경우... | 다음을 수행합니다. 


 a| 
볼륨을 선택합니다
 a| 
.. VVOL 데이터 저장소에 추가할 FlexVol 볼륨을 선택합니다.
.. 스토리지 용량 프로파일 * 열에서 드롭다운 목록을 사용하여 FlexVol 볼륨을 기반으로 새 프로파일을 만들거나 기존 프로파일 중 하나를 선택합니다.
+
자동 생성 기능은 해당 FlexVol 볼륨과 연결된 스토리지 기능을 기반으로 프로파일을 생성합니다. 예: 디스크 유형, 고가용성, 재해 복구, 성능 기능 및 중복 제거.





 a| 
새 볼륨을 생성합니다
 a| 
.. FlexVol의 이름, 크기 및 스토리지 용량 프로필을 입력합니다.
+
애그리게이트는 선택한 스토리지 용량 프로필에 따라 시스템에서 선택됩니다.

.. Auto grow * 옵션을 선택하고 최대 크기를 입력합니다.
.. ADD * 를 클릭하여 FlexVol를 볼륨 목록에 추가합니다.


|===
+
* 알림 *: VVOL 데이터 저장소의 모든 FlexVol 볼륨은 동일한 스토리지 가상 머신(SVM, 이전의 Vserver)에서 가져온 것이어야 합니다.

+
FlexVol 볼륨을 생성한 후 * 수정 * 버튼을 클릭하여 편집할 수 있습니다. 삭제할 수도 있습니다.

. 가상 머신 생성 중에 사용할 기본 스토리지 기능 프로필을 선택하고 * Next * 를 클릭하여 VVOL 데이터 저장소에 추가된 스토리지의 요약을 검토합니다.
. 마침 * 을 클릭합니다.
+
지정한 스토리지가 VVOL 데이터 저장소에 추가됩니다. 완료되면 성공 메시지가 표시됩니다.

+
[NOTE]
====
VVOL 데이터 저장소 * 의 스토리지 확장 마법사는 필요한 모든 ESXi 스토리지 캔이나 기타 중요한 작업을 자동으로 처리합니다. VVOL 데이터 저장소는 VASA Provider에서 제어하는 논리적 엔터티이므로 스토리지 컨테이너의 용량을 늘리기 위해 FlexVol 볼륨을 추가하기만 하면 됩니다.

====

